import {
  selectDocsToolState,
  selectFilesToolState,
  selectFlowToolState,
  selectMemoryToolState,
  selectNotepadToolState,
  selectSkillsToolState,
  selectTasksToolState
} from "./state";

type AnyState = Record<string, any>;

export function selectWorkspaceViewState(args: {
  state: AnyState;
  activeWebTab: unknown;
  filteredFlowForRender: unknown[];
  flowTerminalPhases: string[];
  terminalSessions: Array<{ sessionId: string; title: string; status: string }>;
}): Record<string, unknown> {
  const { state, activeWebTab, filteredFlowForRender, flowTerminalPhases, terminalSessions } = args;
  return {
    chartSource: state.chartSource,
    chartRenderSource: state.chartRenderSource,
    chartError: state.chartError,
    activeWebTab,
    webTabs: state.webTabs,
    activeWebTabId: state.activeWebTabId,
    webHistoryOpen: state.webHistoryOpen,
    webHistoryClearConfirmOpen: state.webHistoryClearConfirmOpen,
    webHistory: state.webHistory,
    webSetupModalOpen: state.webSetupModalOpen,
    webSetupAccount: state.webSetupAccount,
    webSetupApiKey: state.webSetupApiKey,
    webSetupMessage: state.webSetupMessage,
    webSetupBusy: state.webSetupBusy,
    ...selectFilesToolState(state),
    ...selectNotepadToolState(state),
    sheetsState: state.sheetsState,
    ...selectDocsToolState(state),
    ...selectSkillsToolState(state),
    ...selectMemoryToolState(state),
    ...selectTasksToolState(state),
    projectsById: state.projectsById,
    ...selectFlowToolState(state),
    flowTerminalPhases: [...flowTerminalPhases],
    terminalSessions,
    filteredFlowEvents: filteredFlowForRender,
    opencodeState: state.opencodeState,
    looperState: state.looperState
  };
}

export function selectPrimaryPanelState(state: AnyState, chat: unknown): Record<string, unknown> {
  return {
    displayMode: state.displayMode,
    displayModePreference: state.displayModePreference,
    chatRoutePreference: state.chatRoutePreference,
    showAppResourceCpu: state.showAppResourceCpu,
    showAppResourceMemory: state.showAppResourceMemory,
    showAppResourceNetwork: state.showAppResourceNetwork,
    showBottomEngine: state.showBottomEngine,
    showBottomModel: state.showBottomModel,
    showBottomContext: state.showBottomContext,
    showBottomSpeed: state.showBottomSpeed,
    showBottomTtsLatency: state.showBottomTtsLatency,
    chat,
    chatToolIntentByCorrelation: state.chatToolIntentByCorrelation,
    chatFirstAssistantChunkMsByCorrelation: state.chatFirstAssistantChunkMsByCorrelation,
    chatFirstReasoningChunkMsByCorrelation: state.chatFirstReasoningChunkMsByCorrelation,
    chatTtsLatencyMs: state.chatTtsLatencyMs,
    devices: state.devices,
    apiConnections: state.apiConnections,
    apiFormOpen: state.apiFormOpen,
    apiDraft: state.apiDraft,
    apiEditingId: state.apiEditingId,
    apiMessage: state.apiMessage,
    apiSaveBusy: state.apiSaveBusy,
    apiProbeBusy: state.apiProbeBusy,
    apiProbeStatus: state.apiProbeStatus,
    apiProbeMessage: state.apiProbeMessage,
    apiDetectedModels: state.apiDetectedModels,
    conversations: state.conversations,
    llamaRuntime: state.llamaRuntime,
    llamaRuntimeSelectedEngineId: state.llamaRuntimeSelectedEngineId,
    llamaRuntimeModelPath: state.llamaRuntimeModelPath,
    llamaRuntimeActiveModelPath: state.llamaRuntimeActiveModelPath,
    llamaRuntimePort: state.llamaRuntimePort,
    llamaRuntimeCtxSize: state.llamaRuntimeCtxSize,
    llamaRuntimeGpuLayers: state.llamaRuntimeGpuLayers,
    llamaRuntimeThreads: state.llamaRuntimeThreads,
    llamaRuntimeBatchSize: state.llamaRuntimeBatchSize,
    llamaRuntimeUbatchSize: state.llamaRuntimeUbatchSize,
    llamaRuntimeTemperature: state.llamaRuntimeTemperature,
    llamaRuntimeTopP: state.llamaRuntimeTopP,
    llamaRuntimeTopK: state.llamaRuntimeTopK,
    llamaRuntimeRepeatPenalty: state.llamaRuntimeRepeatPenalty,
    llamaRuntimeFlashAttn: state.llamaRuntimeFlashAttn,
    llamaRuntimeMmap: state.llamaRuntimeMmap,
    llamaRuntimeMlock: state.llamaRuntimeMlock,
    llamaRuntimeSeed: state.llamaRuntimeSeed,
    llamaRuntimeMaxTokens: state.llamaRuntimeMaxTokens,
    llamaRuntimeBusy: state.llamaRuntimeBusy,
    llamaRuntimeLogs: state.llamaRuntimeLogs,
    modelManagerInstalled: state.modelManagerInstalled,
    modelManagerActiveTab: state.modelManagerActiveTab,
    modelManagerDisabledModelIds: state.modelManagerDisabledModelIds,
    modelManagerInfoModalModelId: state.modelManagerInfoModalModelId,
    chatModelOptions: state.chatModelOptions,
    allModelsList: state.allModelsList,
    modelManagerQuery: state.modelManagerQuery,
    modelManagerCollection: state.modelManagerCollection,
    modelManagerSearchResults: state.modelManagerSearchResults,
    modelManagerBusy: state.modelManagerBusy,
    modelManagerDownloading: state.modelManagerDownloading,
    modelManagerActiveDownloadKey: state.modelManagerActiveDownloadKey,
    modelManagerActiveDownloadFileName: state.modelManagerActiveDownloadFileName,
    modelManagerActiveDownloadCorrelationId: state.modelManagerActiveDownloadCorrelationId,
    modelManagerDownloadReceivedBytes: state.modelManagerDownloadReceivedBytes,
    modelManagerDownloadTotalBytes: state.modelManagerDownloadTotalBytes,
    modelManagerDownloadPercent: state.modelManagerDownloadPercent,
    modelManagerDownloadSpeedBytesPerSec: state.modelManagerDownloadSpeedBytesPerSec,
    modelManagerMessage: state.modelManagerMessage,
    modelManagerUnslothUdCatalog: state.modelManagerUnslothUdCatalog,
    modelManagerUnslothUdLoading: state.modelManagerUnslothUdLoading,
    stt: state.stt,
    vadMethods: state.vadMethods,
    vadIncludeExperimental: state.vadIncludeExperimental,
    vadSelectedMethod: state.vadSelectedMethod,
    vadShadowMethod: state.vadShadowMethod,
    vadStandbyMethod: state.vadStandbyMethod,
    vadSettings: state.vadSettings,
    voiceRuntimeState: state.voiceRuntimeState,
    voiceHandoffState: state.voiceHandoffState,
    voiceSpeculationState: state.voiceSpeculationState,
    voiceDuplexMode: state.voiceDuplexMode,
    vadShadowSummary: state.vadShadowSummary,
    vadMessage: state.vadMessage,
    tts: state.tts,
    consoleEntries: state.consoleEntries,
    projectsById: state.projectsById,
    projectsSelectedId: state.projectsSelectedId,
    projectsNameDraft: state.projectsNameDraft,
    projectsModalOpen: state.projectsModalOpen,
    avatar: state.avatar,
    avatarActiveTab: state.avatarActiveTab,
    avatarLipSyncStrength: state.avatarLipSyncStrength,
    avatarLipSyncJawBlend: state.avatarLipSyncJawBlend,
    avatarLipSyncJawAmp: state.avatarLipSyncJawAmp,
    avatarLipSyncPhonemeBoost: state.avatarLipSyncPhonemeBoost,
    avatarLipSyncJawMorphScale: state.avatarLipSyncJawMorphScale,
    avatarLipSyncOpenRate: state.avatarLipSyncOpenRate,
    avatarLipSyncCloseRate: state.avatarLipSyncCloseRate,
    avatarLipSyncFallbackRate: state.avatarLipSyncFallbackRate,
    avatarJawBtmX: state.avatarJawBtmX,
    avatarJawBtmY: state.avatarJawBtmY,
    avatarJawBtmZ: state.avatarJawBtmZ,
    avatarJawBtmValue: state.avatarJawBtmValue,
    avatarJawTopX: state.avatarJawTopX,
    avatarJawTopY: state.avatarJawTopY,
    avatarJawTopZ: state.avatarJawTopZ,
    avatarJawTopValue: state.avatarJawTopValue
  };
}
