pub mod agent_tools;
pub mod api_registry;
pub mod app;
pub mod contracts;
pub mod ipc;
pub mod memory;
pub mod observability;
pub mod persistence;
pub mod services;
pub mod stt;
pub mod tools;
#[cfg(feature = "tauri-runtime")]
pub mod tts;
pub mod voice;
pub mod workspace_tools;
